[output]
sort-results = true

[issues]
max-same-issues = 0
fix = false

[linters]
disable = ["godox", "gci"]
enable = ["nlreturn", "varnamelen"]
presets = [
  "bugs",
  "comment",
  "error",
  "format",
  "metalinter",
  "sql",
  "test",
  "unused",
]

[linters-settings.varnamelen]
ignore-names = ["tc"]
