#:schema https://raw.githubusercontent.com/brycekbargar/dotfiles/main/precious-schema.json
[commands."common.EOF"]
type = "tidy"
include = ["*"]
cmd = ["end-of-file-fixer"]
ok_exit_codes = [0, 1]
[commands."common.whitespace"]
type = "tidy"
include = ["*"]
cmd = ["trailing-whitespace-fixer", "--markdown-linebreak-ext=md"]
ok_exit_codes = [0, 1]
[commands."common.large-files"]
type = "lint"
include = ["*"]
cmd = ["check-added-large-files"]
ok_exit_codes = [0]
[commands."common.case"]
type = "lint"
include = ["*"]
cmd = ["check-case-conflict"]
ok_exit_codes = [0]

[commands."go.format"]
type = "tidy"
include = ["*.go"]
cmd = ["golines", "-w", "--max-len=80", "--base-formatter=gofumpt"]
ok_exit_codes = [0]
[commands."go.golangci"]
type = "lint"
include = ["*.go", "go.mod"]
invoke = "once"
path_args = "none"
cmd = [
  "golangci-lint",
  "run",
  "--no-config",
  "--fast",
  "-p",
  "error",
  "-p",
  "format",
  "-p",
  "test",
  "-p",
  "unused",
]
ok_exit_codes = [0]
